max_width = 80

# Ideal width of each line.
# Default: 80
#   max_width = 80

# Maximum width of the args of a function call before
# falling back to vertical formatting.
# Default: 60
#   fn_call_width =

# Maximum width in the body of a struct lit before falling back to vertical formatting.
# Default: 16
#   struct_lit_width =

# Maximum width in the body of a struct variant before falling back to vertical formatting.
# Default: 35
#   struct_variant_width =
